Develop
Yuliya312/react_todo-app pull request #1
Opened 2020-03-11 19:06 UTC by Yuliya312

[DEMO LINK](https://Yuliya312.github.io/react_todo-app/)

2020-03-12 07:31 UTC, irenhh requested changes
![image](https://user-images.githubusercontent.com/33497431/76497203-3d2a7300-6443-11ea-8a59-61f54c407bcc.png)
it should be active ONLY if there is any todo and all of them are checked

add cursor pointer to all interactive elements

2020-03-12 07:31 UTC, irenhh commented on src/App.js
> +
remove this line

2020-03-12 07:31 UTC, irenhh commented on src/components/NewTodo/NewTodo.js
> +    if (event.key === 'Enter' && title.trim().length >= 1) {
add form so that you don't need to find a key name

2020-03-12 07:31 UTC, irenhh commented on src/components/TodoItem/TodoItem.js
> +      className={completed ? 'completed' : ''}
use classnames lib

2020-03-12 07:31 UTC, irenhh commented on src/components/NewTodo/NewTodo.js
> +  static propTypes = {
be consistent about where you write propTypes

2020-03-12 07:31 UTC, irenhh commented on src/components/TodoList/TodoList.js
> +    <>
remove this

2020-03-12 07:31 UTC, irenhh commented on src/components/TodosFilter/TodosFilter.js
> +          ))}
you should close the bracket on the same level you opened it

2020-03-17 08:07 UTC, danheim approved these changes

2020-03-17 08:07 UTC, danheim commented on src/App.js
> +      default:
комбинируй
```suggestion
      case filterButtons.all:
      default:
```

2020-03-17 08:07 UTC, danheim commented on src/App.js
> +    const { filterButtonsChosed, todos } = this.state;
```suggestion
    const { filterField, todos } = this.state;
```

2020-03-17 08:07 UTC, danheim commented on src/components/TodoItem/TodoItem.js
> +  } = props;
не деструктурируй вложенно, делай это отдельно

2020-03-17 08:07 UTC, danheim commented on src/components/TodoList/TodoList.js
> +    <>
remove

2020-03-17 14:26 UTC, merged